name: inadyn # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Internet Automated Dynamic DNS Client
description: |
  Inadyn is a small and simple Dynamic DNS, DDNS, client with HTTPS support.
  Commonly available in many GNU/Linux distributions, used in off the shelf
  routers and Internet gateways to automate the task of keeping your Internet
  name in sync with your public¹ IP address. It can also be used in installations
  with redundant (backup) connections to the Internet.

confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  inadyn:
    command: usr/sbin/inadyn -f ${SNAP_DATA}/inadyn.conf --cache-dir=${SNAP_DATA}
    plugs: [network, network-observe]
  daemon:
    command: usr/sbin/inadyn -n -s -f ${SNAP_DATA}/inadyn.conf --cache-dir=${SNAP_DATA}
    plugs: [network, network-observe]
    daemon: simple
  configpath:
    command: echo ${SNAP_DATA}/inadyn.conf

parts:
  libconfuse:
    plugin: autotools
    source: https://github.com/martinh/libconfuse/releases/download/v3.2/confuse-3.2.tar.gz
    configflags: ['--prefix=/usr', '--disable-examples']
    build-packages:
      - gettext
      - pkg-config

  inadyn:
    plugin: autotools
    source: https://github.com/troglobit/inadyn.git
    source-type: git
    source-commit: f9037b6
    configflags: ['--prefix=/usr', '--sysconfdir=/etc']
    build-packages:
      - libgnutls28-dev
      - pkg-config
    stage-packages:
      - iproute2
      - libgnutls30
    after: [libconfuse]

